language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
script:
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/unittests.js
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/integration.js
env: IMPRESS_MODE=test
